#!/bin/sh
# License: MIT-License
# Source: https://github.com/CrasyCookie/powerinfo
VERSION="1.5.0"

BATTERY="BAT0"
BATTERY_DIRECTORY="/sys/class/power_supply/"
BATTERY_PATH="/$BATTERY_DIRECTORY/$BATTERY/"
CONFIG="/etc/powerinfo"
# Flags, 0 is false and 1 is true
IGNORE_ERRORS=0
WARN_ON_ERROR=0
OUTPUT_RAW=0
OUTPUT_PERCENTAGE=0
OUTPUT_CYCLES=0
OUTPUT_STATUS=0
OUTPUT_THRESHOLDS=0
OUTPUT_CURRENT_CHARGE_OF_MAX_CHARGE=0
OUTPUT_MAX_CHARGE_OF_DESIGN_MAX_CHARGE=0

help() {
    if [ -n "$1" ]; then
        printf "%s. Use powerinfo -h for help or see powerinfo(1).\n" "$1"
    else
        printf "Powerinfo v%s

Usage:
  powerinfo
  powerinfo -h
  powerinfo -cCeEpRstwW CONFIG
Output flags:
  -a              Activates all output flags below.
  -c              Include battery cycles in output.
  -p              Include battery charge percentage in output.
  -s              Include the charging status in output (Charging/Discharging).
  -t              Include set charging thresholds in output.
  -w              Include current charge out of the maximum charge in output.
  -W              Include maximum charge out of design maximum charge in output.
Control flags:
  -B BATTERY      Use alternative battery.
  -C CONFIG       Use alternative configuration file.
  -e              Ignore errors and issue warnings instead.
  -E              Ignore errors silently.
  -h              Display help.
  -R              Raw output, only output values like 80%% and 48.2Wh/57.0Wh.
  -v              Display version number.\n" "$VERSION"
    fi
}
error() {
    # 2 arguments: the error message and exit code.
    if [ "$IGNORE_ERRORS" -eq 1 ]; then
        return 0
    fi
    printf "ERROR: %s" "$1"
    if [ "$WARN_ON_ERROR" -eq 1 ]; then
        printf ", continuing\n"
        return 0
    fi
    printf ", exiting\n"
    exit "$2"
}
if_absent() {
    # 2 arguments: the file to check and the error message on failure
    fail_message="$2"
    if [ -z "$2" ]; then
        fail_message="The file /$1 could not be found"
    fi
    if [ ! -e "$BATTERY_PATH/$1" ]; then
        error "$fail_message" 2
    fi
}
empty_flags() {
    WARN_ON_ERROR=1
    if_absent "capacity"
    OUTPUT_PERCENTAGE=1
    if_absent "cycle_count"
    OUTPUT_CYCLES=1
    if_absent "status"
    OUTPUT_STATUS=1
}
# Source the config if it exists
if [ -f "$CONFIG" ]; then
    . "$CONFIG"
fi

if [ -z "$1" ]; then
    empty_flags
else
    while getopts aB:cC:eEhpRstTvwW FLAGS
    do
        case $FLAGS in
            a)
                if_absent "cycle_count" "Can't check power cycles"
                OUTPUT_CYCLES=1
                if_absent "capacity" "Can't check battery percentage"
                OUTPUT_PERCENTAGE=1
                if_absent "status" "Can't check charging status"
                OUTPUT_STATUS=1
                if_absent "charge_start_threshold" "Can't check charging threshold start"
                if_absent "charge_stop_threshold" "Can't check charging threshold stop"
                OUTPUT_THRESHOLDS=1
                if_absent "energy_now" "Can't check current watt hours of charge."
                if_absent "energy_full" "Can't check maximum watt hours of charge"
                if_absent "energy_full_design" "Can't check design maximum watt hours of charge"
                OUTPUT_CURRENT_CHARGE_OF_MAX_CHARGE=1
                OUTPUT_MAX_CHARGE_OF_DESIGN_MAX_CHARGE=1
                ;;
            B)
                if [ ! -e "/$BATTERY_DIRECTORY/$OPTARG" ]; then
                    error "Specified battery does not exist" 3
                fi
                BATTERY="$OPTARG"
                ;;
            c)
                if_absent "cycle_count" "Can't check power cycles"
                OUTPUT_CYCLES=1
                ;;
            C)
                if [ -f "$OPTARG" ]; then
                    CONFIG="$OPTARG"
                else
                    error "Can't find config file" 4
                fi
                ;;
            e)  WARN_ON_ERROR=1
                ;;
            E)  IGNORE_ERRORS=1
                ;;
            h)
                help
                exit 0
                ;;
            p)
                if_absent "capacity" "Can't check battery percentage"
                OUTPUT_PERCENTAGE=1
                ;;
            R)  OUTPUT_RAW=1
                ;;
            s)
                if_absent "status" "Can't check charging status"
                OUTPUT_STATUS=1
                ;;
            t)
                if_absent "charge_start_threshold" "Can't check charging threshold start"
                if_absent "charge_stop_threshold" "Can't check charging threshold stop"
                OUTPUT_THRESHOLDS=1
                ;;
            v)
                printf "Powerinfo v%s\n" "$VERSION"
                exit 0
                ;;
            w)
                if_absent "energy_now" "Can't check current watt hours of charge."
                if_absent "energy_full" "Can't check maximum watt hours of charge"
                OUTPUT_CURRENT_CHARGE_OF_MAX_CHARGE=1
                ;;
            W)
                if_absent "energy_full" "Can't check maximum watt hours of charge"
                if_absent "energy_full_design" "Can't check design maximum watt hours of charge"
                OUTPUT_MAX_CHARGE_OF_DESIGN_MAX_CHARGE=1
                ;;
            ?)
                help "Unknown parameter"
                exit 1
                ;;
        esac
    done
fi

if [ "$OUTPUT_RAW" -eq 1 ]; then
    if [ "$OUTPUT_PERCENTAGE" -eq 1 ]; then
        percentage_left="$(cat "$BATTERY_PATH/capacity")"
        printf "%s%%\n" "$percentage_left"
    fi
    if [ "$OUTPUT_CYCLES" -eq 1 ]; then
        charge_cycles="$(cat "$BATTERY_PATH/cycle_count")"
        printf "%s\n" "$charge_cycles"
    fi
    if [ "$OUTPUT_STATUS" -eq 1 ]; then
        charging_status="$(printf "%s\n" "$(cat "$BATTERY_PATH/status")" | tr "A-Z" "a-z")"
        printf "%s\n" "$charging_status"
    fi
    if [ "$OUTPUT_THRESHOLDS" -eq 1 ]; then
        charge_start_threshold="$(cat "$BATTERY_PATH/charge_start_threshold")"
        charge_stop_threshold="$(cat "$BATTERY_PATH/charge_stop_threshold")"
        printf "%s%%-%s%%\n" "$charge_start_threshold" "$charge_stop_threshold"
    fi
    if [ "$OUTPUT_CURRENT_CHARGE_OF_MAX_CHARGE" -eq 1 ]; then
        current_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1" "$(cat "$BATTERY_PATH/energy_now")"| bc -lq)"
        full_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1" "$(cat "$BATTERY_PATH/energy_full")" | bc -lq)"
        printf "%sWh/%sWh\n" "$current_energy_watt_hours" "$full_energy_watt_hours"
    fi
    if [ "$OUTPUT_MAX_CHARGE_OF_DESIGN_MAX_CHARGE" -eq 1 ]; then
        full_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1" "$(cat "$BATTERY_PATH/energy_full")" | bc -lq)"
        design_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1" "$(cat "$BATTERY_PATH/energy_full_design")" | bc -lq)"
        printf "%sWh/%sWh\n" "$full_energy_watt_hours" "$design_energy_watt_hours"
    fi
    exit 0
fi
if [ "$OUTPUT_PERCENTAGE" -eq 1 ]; then
    percentage_left="$(cat "$BATTERY_PATH/capacity")"
    printf "%s%% Battery left\n" "$percentage_left"
fi
if [ "$OUTPUT_CYCLES" -eq 1 ]; then
    charge_cycles="$(cat "$BATTERY_PATH/cycle_count")"
    printf "Battery has gone through %s charge cycles\n" "$charge_cycles"
fi
if [ "$OUTPUT_STATUS" -eq 1 ]; then
    charging_status="$(printf "%s\n" "$(cat "$BATTERY_PATH/status")" | tr "A-Z" "a-z")"
    printf "Battery is currently %s\n" "$charging_status"
fi
if [ "$OUTPUT_THRESHOLDS" -eq 1 ]; then
    charge_start_threshold="$(cat "$BATTERY_PATH/charge_start_threshold")"
    charge_stop_threshold="$(cat "$BATTERY_PATH/charge_stop_threshold")"
    printf "Charging starts at %s%% and stops at %s%%\n" "$charge_start_threshold" "$charge_stop_threshold"
fi
if [ "$OUTPUT_CURRENT_CHARGE_OF_MAX_CHARGE" -eq 1 ]; then
    current_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1\n" "$(cat "$BATTERY_PATH/energy_now")" | bc -lq)"
    full_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1\n" "$(cat "$BATTERY_PATH/energy_full")" | bc -lq)"
    printf "Battery currently holds %sWh/%sWh\n" "$current_energy_watt_hours" "$full_energy_watt_hours"
fi
if [ "$OUTPUT_MAX_CHARGE_OF_DESIGN_MAX_CHARGE" -eq 1 ]; then
    full_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1\n" "$(cat "$BATTERY_PATH/energy_full")" | bc -lq)"
    design_energy_watt_hours="$(printf "scale=1; %s / 1000000 / 1\n" "$(cat "$BATTERY_PATH/energy_full_design")" | bc -lq)"
    printf "Battery can hold %sWh/%sWh of charge\n" "$full_energy_watt_hours" "$design_energy_watt_hours"
fi
